
# spring:
#   application:
#     name: api-gateway
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:9000"
  profiles:
    active: dev
    # active: deploy
